# Generated by Django 2.0.2 on 2018-03-03 07:53

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    User = apps.get_model("mariahealth", "User")
    db_alias = schema_editor.connection.alias
    User.objects.using(db_alias).bulk_create([
        User(first_name="Juan", last_name="Dela Cruz"),
        User(first_name="Maria", last_name="Santos"),
    ])

def reverse_func(apps, schema_editor):
    # forwards_func() creates two User instances,
    # so reverse_func() should delete them.
    User = apps.get_model("mariahealth", "User")
    db_alias = schema_editor.connection.alias
    User.objects.using(db_alias).filter(first_name="Juan", last_name="Dela Cruz").delete()
    User.objects.using(db_alias).filter(first_name="Maria", last_name="Santos").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('mariahealth', '0002_auto_20180303_0752'),
    ]

    operations = [
    	migrations.RunPython(forwards_func, reverse_func),
    ]
