# Generated by Django 2.0.2 on 2018-03-03 07:56

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    PaymentTerms = apps.get_model("mariahealth", "PaymentTerms")
    db_alias = schema_editor.connection.alias
    PaymentTerms.objects.using(db_alias).bulk_create([
        PaymentTerms(name="monthly"),
        PaymentTerms(name="quarterly"),
        PaymentTerms(name="annually"),
    ])

def reverse_func(apps, schema_editor):
    # forwards_func() creates two PaymentTerms instances,
    # so reverse_func() should delete them.
    PaymentTerms = apps.get_model("mariahealth", "PaymentTerms")
    db_alias = schema_editor.connection.alias
    PaymentTerms.objects.using(db_alias).filter(name="monthly").delete()
    PaymentTerms.objects.using(db_alias).filter(name="quarterly").delete()
    PaymentTerms.objects.using(db_alias).filter(name="annually").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('mariahealth', '0004_auto_20180303_0754'),
    ]

    operations = [
    	migrations.RunPython(forwards_func, reverse_func),
    ]
