# Generated by Django 2.0.2 on 2018-03-03 07:58

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    HealthPlans = apps.get_model("mariahealth", "HealthPlans")
    PaymentTerms = apps.get_model("mariahealth", "PaymentTerms")
    HMOProvider = apps.get_model("mariahealth", "HMOProvider")

    db_alias = schema_editor.connection.alias
    HealthPlans.objects.using(db_alias).bulk_create([
        HealthPlans(name="PhilCare Luxe", description="All-inclusive health coverage and access to Philcare's network", 
        	cost=16627, payment_terms=PaymentTerms.objects.get(name="annually"), hmo_provider=HMOProvider.objects.get(name="PhilCare")),
        HealthPlans(name="Medi Card Plan", description="All-inclusive health coverage and access to Medicard's network", 
        	cost=18850, payment_terms=PaymentTerms.objects.get(name="annually"), hmo_provider=HMOProvider.objects.get(name="Medi Card")),
        HealthPlans(name="MyMaxiCare", description="All-inclusive health coverage and access to Maxicare's network", 
        	cost=17434, payment_terms=PaymentTerms.objects.get(name="annually"), hmo_provider=HMOProvider.objects.get(name="MaxiCare")),

    ])

def reverse_func(apps, schema_editor):
    # forwards_func() creates two HealthPlans instances,
    # so reverse_func() should delete them.
    HealthPlans = apps.get_model("mariahealth", "HealthPlans")
    db_alias = schema_editor.connection.alias
    HealthPlans.objects.using(db_alias).filter(name="PhilCare Luxe").delete()
    HealthPlans.objects.using(db_alias).filter(name="Medi Card Plan").delete()
    HealthPlans.objects.using(db_alias).filter(name="MyMaxiCare").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('mariahealth', '0005_auto_20180303_0756'),
    ]

    operations = [
    	migrations.RunPython(forwards_func, reverse_func),
    ]
