# Generated by Django 2.0.2 on 2018-03-03 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mariahealth', '0008_auto_20180303_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='PaymentTerms',
            new_name='PaymentTerm',
        ),
        migrations.AddField(
            model_name='cart',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.RenameModel(
            old_name='HealthPlans',
            new_name='HealthPlan',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mariahealth.Cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='health_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mariahealth.HealthPlan'),
        ),
    ]
