# Generated by Django 2.0.2 on 2018-03-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariahealth', '0009_auto_20180303_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
